### ISSUE TITLE
Two functions don't work

### ISSUE THREAD

**Issue by dingearteom** [noscode/demographic_inference_data#1]
2_ButAllA_3_McC and 2_ButSynB2_5_McC fall with an error while being loaded.

Here is a notebook with the error:
https://disk.yandex.ru/d/gIhLhT-gdtcetw

**Comment by noscode** [comment]
Dear @dingearteom,

Thank you very much! I fixed and updated the repo. Please let me know if something is still not working.

Ekaterina

**Comment by dingearteom** [comment]
Thanks, everything works.
